# Generated by Django 4.2.3 on 2023-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='article_slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
