# Generated by Django 4.2.3 on 2023-07-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='datetime',
        ),
    ]
