# Generated by Django 4.2.2 on 2023-07-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
