# Generated by Django 4.2.3 on 2023-07-06 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
